export const EMPRESAS = [
  'Disteandinas',
  'Alpa Construcciones SAS',
  'Super Máquinas',
  'Doranca',
  'Natural Sant Cosmeticos SAS',
  'Pisersa',
  'Inversiones Capira',
  'Intermodal',
  'Laboratorios Decno',
  'Comercializadora LH',
  'Ferreteria La Jimenez SAS',
  'Era Electronica',
  'Centro de Endoscopia Del Valle SAS',
  'Comercializadora Gilza SAS',
  'Artepan',
  'Senco',
  'Fundación Ramirez Moreno',
  'Ferrin SAS',
  'Imporquim Group SAS',
  'Mediser',
  'Expreso Girardota',
  'Intercalco',
  'Proyecciones Plasticas',
  'Corporacion centro de ciencia y tecnologia de Antioquia CTA',
  'Teknum',
  'Distribuidora Químicos Industriales DQI',
  'Reimpex',
  'UnionAgro',
  'Degres',
  'Colombiana de Television',
  'ICIPC',
  'Aceros Industriales',
  'Dormilandia',
  'Alejandro Galvis Ramirez e Hijos SAS',
  'Medvivir',
  'Induali',
  'Vuelven',
  'Core Laboratories',
  'Simelca',
  'Lito',
  'Eypo',
  'Ingelectrica',
  'Osaka',
  'Lumen',
  'Callizo Aroma',
  'Pavimentar',
  'Puro Cuero',
  'Visionamos',
  'Pecoda',
  'Sparcol',
  'Troformas',
  'Carpas Lufer',
  'Acuatubos',
  'Nutriser',
  'C&S Tecnología',
  'Sedic',
  'Helpharma S.A.',
  'Incolab',
  'Transaires',
  'Motor Uno',
  'Star Services',
  'Decoraciones Diego Ramirez',
  'CI Piscicola Botero',
  'CAS Colombia',
  'Expofaro',
  'Levis Strauss',
  'Textiles Guarne',
  'Todoplast',
  'Thomas Greg Seguridad Integral',
  'HPH Inversiones',
  'Organización VID',
  'Serconal',
  'PDT',
  'Hybrytec',
  'Quirumedicas',
  'Convexa',
  'European Pharma Solutions SAS',
  'Brigard Urrutia',
  'Cacharreria Bombay SA',
  'Hermanos Maristas',
  'S&J Full Service',
  'Rayotex',
  'Hotel portal primaveral',
  'Megatoys',
  'Bazar de la Construcción',
  'Ordoñez Herrera',
  'Rambal',
  'Serviconfor',
  'Trading Group',
  'Colarquim',
  'Serfin Educativo SA',
  'Megatienda Super Mayorista SAS',
  'Prolac',
  'Vinos Nobles',
  'Pharmasander',
  'Provias',
  'Serdime',
  'Palmar del Llano',
  'Cinco SAS',
  'Representaciones Hego',
  'Galenicum Vitae Ecuador SAS',
  'PVC Global',
  'Jardines de Paz',
  'Euro Stone SAS',
  'Jmendoza Equipos SAS',
  'Coordinadora de Tanques',
  'Dimotriz',
  'Comercial Tonkin',
  'Hotel Monterrey',
  'Seracis',
  'Disinco SAS',
  'Distribuciones Hernandez & Hernandez',
  'Distribuciones Monarca SAS',
  'Yadich',
  'Integra',
  'One Energy',
  'Mavill',
  'It Certifica',
  'IMD Y CIA SAS',
  'Cootransmede',
  'Higuera Escalante & Cia SAS',
  'Rotoplast',
  'Sensoria Fragancia',
  'RedInstatic',
  'BIOFLUIDOS & FARMA SAS',
  'Mi Celu',
  'Victory Key',
  'Uroclin',
  'Anillos Doble O',
  'Electronic JJ Audio SAS',
  'ETICAP',
  'Undemor',
  'Grupo Gabel',
  'Ciles SAS',
  'Fiza',
  'Coacosta',
  'Colnotex',
  'Termovent SAS',
  'Factor Diferencial',
  'Vila Decoraciones',
  'Pizantex',
  'TCDX',
  'Kababi',
  'Suplacol',
  'Hidrospa',
  'Colmediks',
  'Samara Cosmetic',
  'OpciónTemporal',
  'Biourbe',
  'Arkis',
  'Distribuidora de Mariscos y Pescados de la Sabana',
  'Aress Corredores de Seguros',
  'Coamesa',
  'Carrocerias Panamericana',
  'Cachivaches/Rangun/Morai',
  'Serrano Gomez',
  'Flores Elegancia',
  'Todoterreno',
  'Nueva Empresa SAS',
] as const

export const PRIORIDAD_COLORS: Record<string, string> = {
  URGENTE: 'bg-red-100 text-red-800 border-red-200 dark:bg-red-950 dark:text-red-300',
  ALTA: 'bg-orange-100 text-orange-800 border-orange-200 dark:bg-orange-950 dark:text-orange-300',
  MEDIA: 'bg-yellow-100 text-yellow-800 border-yellow-200 dark:bg-yellow-950 dark:text-yellow-300',
  BAJA: 'bg-blue-100 text-blue-800 border-blue-200 dark:bg-blue-950 dark:text-blue-300',
  'REVISION FORMACION': 'bg-purple-100 text-purple-800 border-purple-200 dark:bg-purple-950 dark:text-purple-300',
  SOLUCIONADO: 'bg-green-100 text-green-800 border-green-200 dark:bg-green-950 dark:text-green-300',
  'DEVOLUCION DE FDS': 'bg-indigo-100 text-indigo-800 border-indigo-200 dark:bg-indigo-950 dark:text-indigo-300',
  'DEVOLUCION DE SERVICIOS': 'bg-cyan-100 text-cyan-800 border-cyan-200 dark:bg-cyan-950 dark:text-cyan-300',
  'REVISIÓN CSM-CLIENTE': 'bg-pink-100 text-pink-800 border-pink-200 dark:bg-pink-950 dark:text-pink-300',
}

export const ESTADO_COLORS: Record<string, string> = {
  'En pruebas': 'bg-yellow-100 text-yellow-800 dark:bg-yellow-950 dark:text-yellow-300',
  'En vivo': 'bg-green-100 text-green-800 dark:bg-green-950 dark:text-green-300',
  Suspendido: 'bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-300',
  'Sin iniciar': 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
}

export const ESTADO_FDS_COLORS: Record<string, string> = {
  Solucionado: 'bg-green-100 text-green-800 dark:bg-green-950 dark:text-green-300',
  Pendiente: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-950 dark:text-yellow-300',
  'En proceso': 'bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-300',
}

export const SEGMENTACION_COLORS: Record<string, string> = {
  'Cambios Enterprise': 'bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-300',
}

export const IMPACTO_COLORS: Record<string, string> = {
  Critico: 'bg-red-100 text-red-800 dark:bg-red-950 dark:text-red-300',
  Alto: 'bg-orange-100 text-orange-800 dark:bg-orange-950 dark:text-orange-300',
  Medio: 'bg-yellow-100 text-yellow-800 dark:bg-yellow-950 dark:text-yellow-300',
  Bajo: 'bg-green-100 text-green-800 dark:bg-green-950 dark:text-green-300',
}
